const infoData = [
    {
        id: 0,
        name: "Intan Fujiati",
        image:
            "https://randomuser.me/api/portraits/women/40.jpg",
        productType: "English",
        price: "68.000,00/Jam",
        pricePremium: "143.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 696,
        number: "(+62) 221 1835 602",
        email: "haryanto.gilda@yahoo.com",
        location: "Tangerang Selatan",
        skill1:"S1 English Yale University",
        skill2:"S2 English University of Cambridge",
        skill3:"Humble",
        statement:"Halo! Perkenalkan nama saya Darsirah Hakim, saya telah berkeja di bidang bangunan selama 10 tahun, saya selalu mengutamakan kerapian dan juga keluetan dalam pekerjaan saya.",
    },
    {
        id: 1,
        name: "Chelsea Kusmawati ",
        image:
            "https://randomuser.me/api/portraits/women/69.jpg",
        productType: "English",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 96,
        number: "(+62) 386 1321 177",
        email: "zprayoga@santoso.id",
        location: "Gading Serpong",
        skill1:"S1 Sastra Inggris Udayana",
        skill2:"2 tahun menjadi guru English",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 2,
        name: "Ajeng Yuliarti",
        image:
            "https://randomuser.me/api/portraits/women/44.jpg",
        productType: "English",
        price: "65.000,00/Jam",
        pricePremium: "140.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 51,
        number: "(+62) 953 2916 564 ",
        email: "sihotang.zelda@yahoo.com",
        location: "Tangerang",
        skill1:"S1 Sastra Inggris Universitas Padjadjaran",
        skill2:"S2 English Oxford University",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },
    {
        id: 3,
        name: "Dartono Wibisono",
        image:
            "https://randomuser.me/api/portraits/men/3.jpg",
        productType: "English",
        price: "47.000,00/Jam",
        pricePremium: "122.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 699,
        number: "(+62) 987 4586 079",
        email: "ramadan.carub@hutasoit.co.id",
        location: "Jakarta Timur",
        skill1:"S1 Sastra Inggris Universitas Udayana",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Humble",
        statement:"EMANG IYA?",
    },
    {
        id: 4,
        name: "Kayla Laksmiwati",
        image:
            "https://randomuser.me/api/portraits/women/91.jpg",
        productType: "English",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 304,
        number: "(+62) 863 525 510",
        email: "xbudiman@wasita.co.id",
        location: "Alam Sutera",
        skill1:"S1 Sastra Diponegoro",
        skill2:"Mengajar untuk kelas 5",
        skill3:"5 tahun menjadi guru English",
        statement:"EMANG IYA?",
    },
    {
        id: 5,
        name: "Daru Mustofa",
        image:
            "https://randomuser.me/api/portraits/men/9.jpg",
        productType: "English",
        price: "57.000,00/Jam",
        pricePremium: "132.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 92,
        number: "(+62) 835 230 423",
        email: "bhasanah@yahoo.co.id",
        location: "Tangerang",
        skill1:"S1 Sastra Inggris Universitas Airlangga",
        skill2:"S2 Sastra Inggris Universitar Indonesia",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },
    {
        id: 6,
        name: "Virman Suryono",
        image:
            "https://randomuser.me/api/portraits/men/32.jpg",
        productType: "English",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 34,
        number: "(+62) 22 1290 196",
        email: "yosef.kuswandari@gmail.com",
        location: "Tangerang Selatan",
        skill1:"S1 Sastra Inggris Universitas Brawijaya",
        skill2:"Mengajar untuk kelas 6",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 7,
        name: "Rini Puspita",
        image:
            "https://randomuser.me/api/portraits/women/8.jpg",
        productType: "English",
        price: "45.000,00/Jam",
        pricePremium: "120.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 88,
        number: "(+62) 360 7703 3924",
        email: "mahesa52@kuswandari.net",
        location: "Jakarta",
        skill1:"S1 Sastra Inggris Universitas Gadjah Mada",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"2 tahun menjadi guru English",
        statement:"EMANG IYA?",
    },
    {
        id: 8,
        name: "Aswani Wacana",
        image:
            "https://randomuser.me/api/portraits/men/59.jpg",
        productType: "English",
        price: "63.000,00/Jam",
        pricePremium: "138.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 27 3159 6484",
        email: "anamaga@waskita.biz",
        location: "Jakarta Selatan",
        skill1:"S1 Sastra Inggris Padjajaran",
        skill2:"Mengajar untuk kelas 1-3",
        skill3:"3 Tahun menjadi guru English",
        statement:"EMANG IYA?",
    },
    {
        id: 9,
        name: "Sabri Habibi",
        image:
            "https://randomuser.me/api/portraits/men/21.jpg",
        productType: "English",
        price: "49.000,00/Jam",
        pricePremium: "124.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62) 527 6444 787",
        email: "cindy31@gmail.co.id",
        location: "Kota Serpong",
        skill1:"S1 Sastra Inggris Universitas Sanata Dharma",
        skill2:"6 Tahun mengajar English",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },

];
export default infoData;