const infoData = [
    {
        id: 0,
        name: "Michael Aditya",
        image:
            "https://randomuser.me/api/portraits/men/39.jpg",
        productType: "Matematika",
        price: "55.000,00/Jam",
        pricePremium: "130.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 62,
        number: "(+62) 395 4625 800",
        email: "nabila62@lailasari.tv",
        location: "Tangerang Selatan",
        skill1:"S1 Matematika Universitas Hasanuddin",
        skill2:"Juara 3 Olympiade Matematika",
        skill3:"Mudah Bergaul",
        statement:"Halo! Perkenalkan nama saya Darsirah Hakim, saya telah berkeja di bidang bangunan selama 10 tahun, saya selalu mengutamakan kerapian dan juga keluetan dalam pekerjaan saya.",
    },
    {
        id: 1,
        name: "Gadang Halim",
        image:
            "https://randomuser.me/api/portraits/men/37.jpg",
        productType: "Matematika",
        price: "57.000,00/Jam",
        pricePremium: "132.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62) 590 7653 6594",
        email: "eja.mulyani@pradipta.net",
        location: "Jakarta Barat",
        skill1:"S1 Statistika Universitas Sriwijaya",
        skill2:"S2 Matematika Universitas Brawijaya",
        skill3:"1 tahun menjadi guru Matematika",
        statement:"EMANG IYA?",
    },
    {
        id: 2,
        name: "Purwanto Pangestu",
        image:
            "https://randomuser.me/api/portraits/men/38.jpg",
        productType: "Matematika",
        price: "50.000,00/Jam",
        pricePremium: "125.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 61,
        number: "(+62) 229 9251 4683",
        email: "rudi.namaga@mansur.net",
        location: "Tangerang",
        skill1:"S1 Statistika Institut Teknologi Bandung",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 3,
        name: "Eli Nuraini",
        image:
            "https://randomuser.me/api/portraits/women/7.jpg",
        productType: "Matematika",
        price: "47.000,00/Jam",
        pricePremium: "122.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62) 675 8887 7023",
        email: "kiandra02@gmail.co.id",
        location: "Jakarta Timur",
        skill1:"S1 Matematika Binus University",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Menjadi guru Matematika selama 2 tahun",
        statement:"EMANG IYA?",
    },
    {
        id: 4,
        name: "Adiarja Salahudin",
        image:
            "https://randomuser.me/api/portraits/men/34.jpg",
        productType: "Matematika",
        price: "50.000,00/Jam",
        pricePremium: "125.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 304,
        number: "(+62) 989 5014 443",
        email: "kala91@gmail.co.id",
        location: "Alam Sutera",
        skill1:"S1 Matematika Universitas Diponegoro",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"3 tahun menjadi guru Matematika",
        statement:"EMANG IYA?",
    },
    {
        id: 5,
        name: "Dinda Winarsih",
        image:
            "https://randomuser.me/api/portraits/women/37.jpg",
        productType: "Matematika",
        price: "77.000,00/Jam",
        pricePremium: "152.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 92,
        number: "(+62) 24 8005 1781",
        email: "wardaya.winarno@gmail.com",
        location: "Tangerang",
        skill1:"S1 Matematika Institut Teknologi Sepuluh Nopember",
        skill2:"S2 Statistika Institut Teknologi Bandung",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },
    {
        id: 6,
        name: "Karja Rajata",
        image:
            "https://randomuser.me/api/portraits/men/0.jpg",
        productType: "Matematika",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 34,
        number: "(+62) 874 1317 5390",
        email: "maryati.harjo@suryono.or.id",
        location: "Tangerang Selatan",
        skill1:"S1 Statistika Universitas Gadjah Mada",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 7,
        name: "Rini Mandasari",
        image:
            "https://randomuser.me/api/portraits/women/0.jpg",
        productType: "Matematika",
        price: "55.000,00/Jam",
        pricePremium: "130.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 80,
        number: "(+62) 869 6928 890",
        email: "jindra24@yahoo.co.id",
        location: "Jakarta",
        skill1:"S1 Matematika Universitas Sebelas Maret",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"4 tahun menjadi guru Matematika",
        statement:"EMANG IYA?",
    },
    {
        id: 8,
        name: "Makuta Marpaung",
        image:
            "https://randomuser.me/api/portraits/men/95.jpg",
        productType: "Matematika",
        price: "63.000,00/Jam",
        pricePremium: "138.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 822 614 959",
        email: "opuspita@yahoo.co.id",
        location: "Jakarta Selatan",
        skill1:"S1 Matematika Binus University ",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"2 Tahun menjadi guru Matematika",
        statement:"EMANG IYA?",
    },
    {
        id: 9,
        name: "Winda Mulyani",
        image:
            "https://randomuser.me/api/portraits/women/89.jpg",
        productType: "Matematika",
        price: "57.000,00/Jam",
        pricePremium: "132.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62) 532 6688 2561",
        email: "cahyadi.pertiwi@yahoo.com",
        location: "Tangerang Barat",
        skill1:"S1 Statistika Universitas Airlangga",
        skill2:"3 Tahun mengajar Matematika",
        skill3:"Mengajar untuk kelas 6",
        statement:"EMANG IYA?",
    },

];
export default infoData;