const infoData = [
    {
        id: 0,
        name: "Titin Novitasari (Female)",
        image:
            "https://randomuser.me/api/portraits/men/50.jpg",
        productType: "Cleaning Service",
        price: "46.000,00/Hari",
        pricePremium: "121.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 53,
        number: "(+62) 408 1746 4923",
        email: "narpati.hana@laksita.mil.id",
        location: "Tanggerang",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 1,
        name: "Panca Pradipta",
        image:
            "https://randomuser.me/api/portraits/men/6.jpg",
        productType: "Cleaning Service",
        price: "51.000,00/Hari",
        pricePremium: "126.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62) 720 6067 614",
        email: "kala.purnawati@prasetya.or.id",
        location: "Tanggerang",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 2,
        name: "Padma Prastuti (Female)",
        image:
            "https://randomuser.me/api/portraits/men/73.jpg",
        productType: "Cleaning Service",
        price: "122.000,00/Hari",
        pricePremium: "197.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 51,
        number: "(+62) 927 4522 2207",
        email: "prasetya.halim@gmail.com",
        location: "Tangggerang",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 3,
        name: "Elvina Rahmawati (Female)",
        image:
            "https://randomuser.me/api/portraits/men/83.jpg",
        productType: "Cleaning Service",
        price: "200.000,00/Hari",
        pricePremium: "275.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62) 985 8801 7902",
        email: "natsir.tania@ardianto.go.id",
        location: "Alam Sutera",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 4,
        name: "Taswir Prasasta",
        image:
            "https://randomuser.me/api/portraits/men/52.jpg",
        productType: "Cleaning Service",
        price: "167.000,00/Hari",
        pricePremium: "242.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 304,
        number: "(+62) 576 9650 7132",
        email: "cakrawala69@yahoo.co.id",
        location: "Alam Sutera",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 5,
        name: "Viman Hakim",
        image:
            "https://randomuser.me/api/portraits/men/9.jpg",
        productType: "Cleaning Service",
        price: "71.000,00/Hari",
        pricePremium: "146.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 162,
        number: "(+62)024 0839 945",
        email: "cemeti.utami@gmail.com",
        location: "Tanggerang",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 6,
        name: "Hilda Yolanda (Female)",
        image:
            "https://randomuser.me/api/portraits/men/65.jpg",
        productType: "Cleaning Service",
        price: "151.000,00/Hari",
        pricePremium: "226.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 19,
        number: "(+62)353 6320 000 ",
        email: "laksmiwati.kusuma@yahoo.com",
        location: "Gading Serpong",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 7,
        name: "Janet Susanti (Female)",
        image:
            "https://randomuser.me/api/portraits/men/48.jpg",
        productType: "Cleaning Service",
        price: "212.000,00/Hari",
        pricePremium: "287.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 55,
        number: "(+62)965 5627 159",
        email: "puji.wacana@anggraini.my.id",
        location: "Gading Serpong",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 8,
        name: "Najib Firmansyah",
        image:
            "https://randomuser.me/api/portraits/men/45.jpg",
        productType: "Cleaning Service",
        price: "53.000,00/Hari",
        pricePremium: "128.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62)425 3178 422",
        email: "hesti37@yahoo.com",
        location: "Gading Serpong",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },
    {
        id: 9,
        name: "Ratna Melani (Female)",
        image:
            "https://randomuser.me/api/portraits/men/31.jpg",
        productType: "Cleaning Service",
        price: "87.000,00/Hari",
        pricePremium: "162.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62)909 9166 651",
        email: "hassanah.kamaria@gmail.com",
        location: "Jakarta Barat",
        skill1: "Saya akan menjamin kebersihan rumah anda!",
        skill2: "Saya bekerja dengan cepat dan efisien",
        skill3: "saya akan menjamin kerapian rumah anda",
        statement: "mang eak?",
    },

];
export default infoData;