const infoData = [
    {
        id: 0,
        name: "Darsirah Hakim",
        image:
            "https://randomuser.me/api/portraits/men/50.jpg",
        productType: "WC Care",
        price: "73.000,00/Hari",
        pricePremium: "148.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 53,
        number: "(+62) 786 8353 9273",
        email: "ajeng.sihotang@sitompul.co",
        location: "Ki. Bappenas No. 765, Administrasi Jakarta Timur 12151, SumSel",
        skill1:"Instalasi Pipa",
        skill2:"Instalasi Water Heater",
        skill3:"Instalasi Pompa",
        statement:"Halo! Perkenalkan nama saya Darsirah Hakim, saya telah berkeja di bidang bangunan selama 10 tahun, saya selalu mengutamakan kerapian dan juga keluetan dalam pekerjaan saya.",
    },
    {
        id: 1,
        name: "Gading Rajata",
        image:
            "https://randomuser.me/api/portraits/men/6.jpg",
        productType: "Ahli Sedot WC",
        price: "51.000,00/Hari",
        pricePremium: "126.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62) 478 9932 6219",
        email: "znamaga@oktaviani.id",
        location: "Jr. Pasirkoja No. 990, Mataram 99662, SumBar",
        skill1:"Instalasi Pipa",
        skill2:"Perbaikan Pipa",
        skill3:"Pembersih Septic Tank",
        statement:"EMANG IYA?",
    },
    {
        id: 2,
        name: "Ganda Januar",
        image:
            "https://randomuser.me/api/portraits/men/73.jpg",
        productType: "Instalasi Perangkat WC",
        price: "122.000,00/Hari",
        pricePremium: "197.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 51,
        number: "(+62) 210 9540 051",
        email: "melani.umi@gmail.co.id ",
        location: "Psr. Imam No. 953, Cirebon 73230, SumUt",
        skill1:"Instalasi Pipa",
        skill2:"Instalasi Water Heater",
        skill3:"Instalasi Pompa",
        statement:"EMANG IYA?",
    },
    {
        id: 3,
        name: "Daniswara Lazuardi",
        image:
            "https://randomuser.me/api/portraits/men/83.jpg",
        productType: "Toilet Intensive Care",
        price: "200.000,00/Hari",
        pricePremium: "275.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62) 582 9684 731",
        email: "oskar75@winarsih.desa.id ",
        location: "Kpg. Hang No. 628, Denpasar 94292, SumUt",
        skill1:"Pembersihan Intensive Toilet",
        skill2:"Kerapian Pengerjaan",
        skill3:"Efisiensi Pengerjaan",
        statement:"EMANG IYA?",
    },
    {
        id: 4,
        name: "Baktianto Prasetya",
        image:
            "https://randomuser.me/api/portraits/men/52.jpg",
        productType: "WC Maintenance",
        price: "167.000,00/Hari",
        pricePremium: "242.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 304,
        number: "(+62) 304 9954 726",
        email: "titi.hassanah@suartini.net ",
        location: "Ds. Sukajadi No. 424, Bandung 39441, SulSel",
        skill1:"Perbaikan Closet Tersumbat",
        skill2:"Perbaikan Pipa",
        skill3:"Pembersih Septic Tank",
        statement:"EMANG IYA?",
    },
    {
        id: 5,
        name: "Marsito Haryanto",
        image:
            "https://randomuser.me/api/portraits/men/9.jpg",
        productType: "Ahli Pompa WC",
        price: "71.000,00/Hari",
        pricePremium: "146.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 162,
        number: "(+62) 561 8229 162",
        email: "nugraha41@namaga.biz ",
        location: "Psr. Padma No. 902, Bandung 75602, KalTim",
        skill1:"Instalasi Pompa",
        skill2:"Perbaikan Pompa",
        skill3:"Perbaikan Pipa",
        statement:"EMANG IYA?",
    },
    {
        id: 6,
        name: "Wira Hardiansyah",
        image:
            "https://randomuser.me/api/portraits/men/65.jpg",
        productType: "Ahli Pipa",
        price: "151.000,00/Hari",
        pricePremium: "226.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 19,
        number: "(+62) 809 199 314",
        email: "dian.laksita@yahoo.co.id",
        location: "Gg. Merdeka No. 415, Padang 50476, SulTeng",
        skill1:"Perbaikan Pipa",
        skill2:"Perbaikan Closet Tersumbat",
        skill3:"Instalasi Pipa",
        statement:"EMANG IYA?",
    },
    {
        id: 7,
        name: "Vero Habibi",
        image:
            "https://randomuser.me/api/portraits/men/48.jpg",
        productType: "Instalasi Shower",
        price: "212.000,00/Hari",
        pricePremium: "287.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 55,
        number: "(+62) 455 5447 6922",
        email: "uyainah.saiful@gmail.com ",
        location: "Jln. Baiduri No. 122, Pekalongan 21340, Bengkulu",
        skill1:"Instalasi Shower",
        skill2:"Instalasi Water Heater",
        skill3:"Instalasi Pompa",
        statement:"EMANG IYA?",
    },
    {
        id: 8,
        name: "Ilyas Ramadanv",
        image:
            "https://randomuser.me/api/portraits/men/45.jpg",
        productType: "WC Cleaner Service",
        price: "53.000,00/Hari",
        pricePremium: "128.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 631 9158 678",
        email: "uyainah.olivia@gmail.co.id ",
        location: "Ds. Salak No. 308, Jayapura 87038, Bali",
        skill1:"Kerapian Pengerjaan",
        skill2:"Efisiensi Pembersihaan Toilet",
        skill3:"Pembersihan Intensive Toilet",
        statement:"EMANG IYA?",
    },
    {
        id: 9,
        name: "Leo Santoso",
        image:
            "https://randomuser.me/api/portraits/men/31.jpg",
        productType: "Reparasi dan Maintenance WC",
        price: "87.000,00/Hari",
        pricePremium: "162.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62) 816 3337 970",
        email: "cnarpati@yahoo.com",
        location: "Gg. Gotong Royong No. 605, Sungai Penuh 28915, SulBar",
        skill1:"Reparasi Pipa",
        skill2:"Reparasi Pompa",
        skill3:"Reparasi Perangkat WC",
        statement:"EMANG IYA?",
    },

];
export default infoData;