const infoData = [
    {
        id: 0,
        name: "Heryanto Budiyanto",
        image:
            "https://randomuser.me/api/portraits/men/50.jpg",
        productType: "Service Mobil",
        price: "46.000,00/Hari",
        pricePremium: "121.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 53,
        number: "(+62) 340 1499 027",
        email: "permata.dalima@yahoo.co.id",
        location: "Tanggerang",
        skill1:"Check up mobil (Free!)",
        skill2:"Reparasi mesin mobil",
        skill3:"Maintanance mobil",
        statement:"Halo! Perkenalkan nama saya Darsirah Hakim, saya telah berkeja di bidang bangunan selama 10 tahun, saya selalu mengutamakan kerapian dan juga keluetan dalam pekerjaan saya.",
    },
    {
        id: 1,
        name: "Lasmanto Winarno",
        image:
            "https://randomuser.me/api/portraits/men/6.jpg",
        productType: "Service Mobil",
        price: "51.000,00/Hari",
        pricePremium: "126.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62) 436 4915 9631",
        email: "permata.dalima@yahoo.co.id",
        location: "Alam Sutera",
        skill1:"Check up mobil (Free!)",
        skill2:"Reparasi interior mobil",
        skill3:"Reparasi mesin mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 2,
        name: "Lasmono Saragih",
        image:
            "https://randomuser.me/api/portraits/men/73.jpg",
        productType: "Reparasi dan Maintanance",
        price: "122.000,00/Hari",
        pricePremium: "197.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 51,
        number: "(+62) 864 5903 378",
        email: "imaryati@yahoo.co.id",
        location: "Gading Serpong",
        skill1:"Check up mobil (Free!)",
        skill2:"Reparasi mesin mobil",
        skill3:"Maintanance mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 3,
        name: "Satya Prasasta",
        image:
            "https://randomuser.me/api/portraits/men/83.jpg",
        productType: "Reparasi dan Perawatan",
        price: "200.000,00/Hari",
        pricePremium: "275.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62) 470 3422 056",
        email: "olga87@gmail.com",
        location: "Tanggerang",
        skill1:"Check up mobil (Free!)",
        skill2:"Reparasi interior mobil",
        skill3:"Reparasi mesin mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 4,
        name: "Baktianto Prasetya",
        image:
            "https://randomuser.me/api/portraits/men/52.jpg",
        productType: "Modifikasi",
        price: "167.000,00/Hari",
        pricePremium: "242.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 304,
        number: "(+62) 304 9954 726",
        email: "titi.hassanah@suartini.net ",
        location: "Ds. Sukajadi No. 424, Bandung 39441, SulSel",
        skill1:"Check up mobil (Free!)",
        skill2:"Modifikasi mesin mobil",
        skill3:"Modifikasi interior mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 5,
        name: "Jefri Dabukke",
        image:
            "https://randomuser.me/api/portraits/men/9.jpg",
        productType: "Modifikasi dan Tuning",
        price: "71.000,00/Hari",
        pricePremium: "146.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 162,
        number: "(+62) 532 4885 8258",
        email: "mahmud.uyainah@gmail.co.id",
        location: "Tanggerang",
        skill1:"Check up mobil (Free!)",
        skill2:"Modifikasi interior mobil",
        skill3:"Modifikasi mesin mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 6,
        name: "Edison Latupono",
        image:
            "https://randomuser.me/api/portraits/men/65.jpg",
        productType: "Mesin dan Sparepart",
        price: "151.000,00/Hari",
        pricePremium: "226.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 19,
        number: "(+62) 518 1641 380",
        email: "edward69@yahoo.com",
        location: "Tanggerang",
        skill1:"Check up mobil (Free!)",
        skill2:"Modifikasi mesin mobil",
        skill3:"Reparasi mesin mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 7,
        name: "Dalimin Hutagalung",
        image:
            "https://randomuser.me/api/portraits/men/48.jpg",
        productType: "Modifikasi Interior",
        price: "212.000,00/Hari",
        pricePremium: "287.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 55,
        number: "(+62) 658 2985 2005",
        email: "palastri.maya@halimah.web.id",
        location: "Alam Sutera",
        skill1:"Check up mobil (Free!)",
        skill2:"Reparasi interior mobil",
        skill3:"Modifikasi interior mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 8,
        name: "Baktianto Kurniawan",
        image:
            "https://randomuser.me/api/portraits/men/45.jpg",
        productType: "Modifikasi dan Maintenance",
        price: "53.000,00/Hari",
        pricePremium: "128.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 233 0533 015",
        email: "langgeng47@gmail.com",
        location: "Gading Serpong",
        skill1:"Check up mobil (Free!)",
        skill2:"Maintanance mobil",
        skill3:"Modifikasi interior mobil",
        statement:"EMANG IYA?",
    },
    {
        id: 9,
        name: "Mahmud Najmudin",
        image:
            "https://randomuser.me/api/portraits/men/31.jpg",
        productType: "Reparasi dan Maintenance",
        price: "87.000,00/Hari",
        pricePremium: "162.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62) 473 0040 6109",
        email: "ksimbolon@yahoo.co.id",
        location: "Gading Serpong",
        skill1:"Check up mobil (Free!)",
        skill2:"Reparasi mesin mobil",
        skill3:"Maintenance mobil",
        statement:"EMANG IYA?",
    },

];
export default infoData;