const infoData = [
    {
        id: 0,
        name: "Eka Prastuti",
        image:
            "https://randomuser.me/api/portraits/women/50.jpg",
        productType: "Bahasa Indonesia",
        price: "55.000,00/Jam",
        pricePremium: "130.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 52,
        number: "(+62) 030 8353 9273",
        email: "pudjiastuti.ibrani@yahoo.co.id",
        location: "Tangerang Selatan",
        skill1:"S1 Sastra Indonesia Universitas Indonesia",
        skill2:"Juara 1 Menulis Cerpen Nasional",
        skill3:"Mudah Bergaul",
        statement:"Halo! Perkenalkan nama saya Darsirah Hakim, saya telah berkeja di bidang bangunan selama 10 tahun, saya selalu mengutamakan kerapian dan juga keluetan dalam pekerjaan saya.",
    },
    {
        id: 1,
        name: "Elma Nurdiyanti",
        image:
            "https://randomuser.me/api/portraits/women/6.jpg",
        productType: "Bahasa Indonesia",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62) 312 2294 779",
        email: "lsaputra@yahoo.com",
        location: "Jakarta Barat",
        skill1:"S1 Sastra Indonesia Universitas Negeri Semarang",
        skill2:"7 tahun menjadi guru Bahasa Indonesia",
        skill3:"-",
        statement:"EMANG IYA?",
    },
    {
        id: 2,
        name: "Cici Zulaika",
        image:
            "https://randomuser.me/api/portraits/women/73.jpg",
        productType: "Bahasa Indonesia",
        price: "50.000,00/Jam",
        pricePremium: "125.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 51,
        number: "(+62) 960 2893 254",
        email: "ddamanik@gmail.com",
        location: "Tangerang",
        skill1:"S1 Sastra Indonesia Universitas Padjadjaran",
        skill2:"Mengajar untuk kelas 3-6",
        skill3:"Juara 2 Puisi Kabupaten Bandung",
        statement:"EMANG IYA?",
    },
    {
        id: 3,
        name: "Rusman Nashiruddin",
        image:
            "https://randomuser.me/api/portraits/men/83.jpg",
        productType: "Bahasa Indonesia",
        price: "47.000,00/Jam",
        pricePremium: "122.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62) 201 7511 388",
        email: "vhidayat@yahoo.com",
        location: "Jakarta Timur",
        skill1:"S1 Sastra Indonesia Universitas Negeri Jember",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 4,
        name: "Bella Hasanah",
        image:
            "https://randomuser.me/api/portraits/women/52.jpg",
        productType: "Bahasa Indonesia",
        price: "50.000,00/Jam",
        pricePremium: "125.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 304,
        number: "(+62) 616 4190 296",
        email: "padmi60@gmail.co.id",
        location: "Alam Sutera",
        skill1:"S1 Sastra Indonesia Universitas Udayana Bali",
        skill2:"Mengajar untuk kelas 5",
        skill3:"5 tahun menjadi guru Bahasa Indonesia",
        statement:"EMANG IYA?",
    },
    {
        id: 5,
        name: "Jasmin Farida",
        image:
            "https://randomuser.me/api/portraits/women/9.jpg",
        productType: "Bahasa Indonesia",
        price: "57.000,00/Jam",
        pricePremium: "132.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 92,
        number: "(+62) 771 0623 115",
        email: "qkuswandari@purwanti.desa.id",
        location: "Tangerang",
        skill1:"S1 Sastra Indonesia Universitas Pendidikan Indonesia",
        skill2:"S2 Sastra Indonesia Universitar Indonesia",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },
    {
        id: 6,
        name: "Viman Putra",
        image:
            "https://randomuser.me/api/portraits/men/65.jpg",
        productType: "Bahasa Indonesia",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 34,
        number: "(+62) 670 6734 6071",
        email: "paris.suryono@hidayanto.or.id",
        location: "Tangerang Selatan",
        skill1:"S1 Sastra Indonesia Universitas Diponegoro",
        skill2:"Mengajar untuk kelas 6",
        skill3:"-",
        statement:"EMANG IYA?",
    },
    {
        id: 7,
        name: "Cemplunk Suwarno",
        image:
            "https://randomuser.me/api/portraits/men/48.jpg",
        productType: "Bahasa Indonesia",
        price: "45.000,00/Jam",
        pricePremium: "120.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 80,
        number: "(+62) 958 9651 2259",
        email: "wlestari@farida.desa.id",
        location: "Jakarta",
        skill1:"S1 Sastra Indonesia Universitas Pendidikan Indonesia",
        skill2:"Mengajar untuk kelas 1-4",
        skill3:"1 tahun menjadi guru Bahasa Indonesia",
        statement:"EMANG IYA?",
    },
    {
        id: 8,
        name: "Lanang Zulkarnain",
        image:
            "https://randomuser.me/api/portraits/men/45.jpg",
        productType: "Bahasa Indonesia",
        price: "63.000,00/Jam",
        pricePremium: "138.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 617 6412 286",
        email: "ahastuti@pranowo.id",
        location: "Jakarta Selatan",
        skill1:"S1 Sastra Indonesia Universitas Gadjah Mada",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"1.5 Tahun menjadi guru Bahasa Indonesia",
        statement:"EMANG IYA?",
    },
    {
        id: 9,
        name: "Rina Novitasari",
        image:
            "https://randomuser.me/api/portraits/women/31.jpg",
        productType: "Bahasa Indonesia",
        price: "47.000,00/Jam",
        pricePremium: "122.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62) 362 5573 689",
        email: "ramadan.nalar@tarihoran.co",
        location: "Kota Serpong",
        skill1:"S1 Sastra Indonesia Universitas Sanata Dharma",
        skill2:"3 Tahun mengajar Bahasa Indonesia kelas 6 di Pangudi Luhur Bernardus",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },

];
export default infoData;