const infoData = [
    {
        id: 0,
        name: "Tri Zulkarnain",
        image:
            "https://randomuser.me/api/portraits/men/50.jpg",
        price: "46.000,00/Hari",
        pricePremium: "121.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 53,
        number: "(+62)475 0973 8392",
        email: "adriansyah.karja@yahoo.co.id",
        location: "Tangerang",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 1,
        name: "Heru Hutasoit",
        image:
            "https://randomuser.me/api/portraits/men/6.jpg",
        price: "51.000,00/Hari",
        pricePremium: "126.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62)965 0491 3240",
        email: "viktor.wacana@oktaviani.co.id",
        location: "Tangerang",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 2,
        name: "Emin Uwais",
        image:
            "https://randomuser.me/api/portraits/men/73.jpg",
        
        price: "122.000,00/Hari",
        pricePremium: "197.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 51,
        number: "(+62)550 5708 9089",
        email: "rajasa.zelda@salahudin.go.id",
        location: "Tangerang",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 3,
        name: "Malik Wasita",
        image:
            "https://randomuser.me/api/portraits/men/83.jpg",
        
        price: "200.000,00/Hari",
        pricePremium: "275.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62)0824 9063 778",
        email: "hutapea.zizi@laksita.com",
        location: "Alam Sutera",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 4,
        name: "Karma Tamba",
        image:
            "https://randomuser.me/api/portraits/men/52.jpg",
        
        price: "167.000,00/Hari",
        pricePremium: "242.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 304,
        number: "(+62)544 4609 522",
        email: "sitompul.gamanto@lestari.or.id",
        location: "Alam Sutera",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 5,
        name: "Taswir Prasasta",
        image:
            "https://randomuser.me/api/portraits/men/9.jpg",
        
        price: "71.000,00/Hari",
        pricePremium: "146.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 162,
        number: "(+62)0504 4702 9787",
        email: "narpati.kamaria@yahoo.com",
        location: "Alam Sutera",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 6,
        name: "Cemeti Budiman",
        image:
            "https://randomuser.me/api/portraits/men/65.jpg",
        
        price: "151.000,00/Hari",
        pricePremium: "226.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 19,
        number: "(+62) 353 6320 000",
        email: "laksmiwati.kusuma@yahoo.com",
        location: "Gading Serpong",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 7,
        name: "Okto Simbolon",
        image:
            "https://randomuser.me/api/portraits/men/48.jpg",
        
        price: "212.000,00/Hari",
        pricePremium: "287.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 55,
        number: "(+62)965 5627 159 ",
        email: "puji.wacana@anggraini.my.id",
        location: "Gading Serpong",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 8,
        name: "Joko Saefullah",
        image:
            "https://randomuser.me/api/portraits/men/45.jpg",
        
        price: "53.000,00/Hari",
        pricePremium: "128.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 425 3178 422",
        email: "hesti37@yahoo.com",
        location: "Gading Serpong",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },
    {
        id: 9,
        name: "Prabowo Wahyudin",
        image:
            "https://randomuser.me/api/portraits/men/31.jpg",
        
        price: "87.000,00/Hari",
        pricePremium: "162.000,00/Hari",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62)909 9166 651 ",
        email: "hassanah.kamaria@gmail.com",
        location: "Jakarta Barat",
        productType: "Service dan Perawatan AC",
        skill1: "Cuci AC",
        skill2: "Maintenance AC",
        skill3: "Reparasi AC",
        statement: "mang eak?",
    },

];
export default infoData;