const infoData = [
    {
        id: 0,
        name: "Purwa Hutasoit",
        image:
            "https://randomuser.me/api/portraits/men/2.jpg",
        productType: "IPA",
        price: "55.000,00/Jam",
        pricePremium: "130.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 62,
        number: "(+62) 390 5565 870",
        email: "nabila62@lailasari.tv",
        location: "Tangerang Barat",
        skill1:"S1 Fisika Universitas Hasanuddin",
        skill2:"Juara 1 Olympiade Physics Festival",
        skill3:"Mudah Bergaul",
        statement:"Halo! Perkenalkan nama saya Darsirah Hakim, saya telah berkeja di bidang bangunan selama 10 tahun, saya selalu mengutamakan kerapian dan juga keluetan dalam pekerjaan saya.",
    },
    {
        id: 1,
        name: "Darimin Hidayanto",
        image:
            "https://randomuser.me/api/portraits/men/5.jpg",
        productType: "IPA",
        price: "57.000,00/Jam",
        pricePremium: "132.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 99,
        number: "(+62) 845 6951 9728",
        email: "warji62@gmail.com",
        location: "Jakarta Barat",
        skill1:"S1 Kimia Murni Universitas Sriwijaya",
        skill2:"S2 Biologi Universitas Brawijaya",
        skill3:"3 tahun menjadi guru IPA",
        statement:"EMANG IYA?",
    },
    {
        id: 2,
        name: "Tantri Kusmawati",
        image:
            "https://randomuser.me/api/portraits/women/1.jpg",
        productType: "IPA",
        price: "50.000,00/Jam",
        pricePremium: "125.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 61,
        number: "(+62) 768 7656 594",
        email: "gasti.yolanda@gmail.co.id",
        location: "Tangerang",
        skill1:"S1 Biologi Institut Teknologi Bandung",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Bersahabat",
        statement:"EMANG IYA?",
    },
    {
        id: 3,
        name: "Kawaya Saputra",
        image:
            "https://randomuser.me/api/portraits/men/7.jpg",
        productType: "IPA",
        price: "47.000,00/Jam",
        pricePremium: "122.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 328,
        number: "(+62) 25 3118 364",
        email: "habibi.leo@sitompul.co.id",
        location: "Jakarta Timur",
        skill1:"S1 Kimia Murni Universitas Sumatera Utara",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 4,
        name: "Gangsar Widodo",
        image:
            "https://randomuser.me/api/portraits/women/52.jpg",
        productType: "IPA",
        price: "50.000,00/Jam",
        pricePremium: "125.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 304,
        number: "(+62) 759 1901 4323 ",
        email: "tasnim04@gmail.co.id",
        location: "Alam Sutera",
        skill1:"S1 Kimia Indonesia Universitas Diponegoro",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"5 tahun menjadi guru IPA",
        statement:"EMANG IYA?",
    },
    {
        id: 5,
        name: "Lembah Sihombing",
        image:
            "https://randomuser.me/api/portraits/men/5.jpg",
        productType: "IPA",
        price: "77.000,00/Jam",
        pricePremium: "152.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 92,
        number: "(+62) 892 8216 663",
        email: "elon14@yahoo.co.id",
        location: "Tangerang",
        skill1:"S1 Fisika Institut Teknologi Sepuluh Nopember",
        skill2:"S2 Biologi Institut Pertanian Bogor",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },
    {
        id: 6,
        name: "Dinda Suartini",
        image:
            "https://randomuser.me/api/portraits/women/10.jpg",
        productType: "IPA",
        price: "51.000,00/Jam",
        pricePremium: "126.000,00/Jam",
        rating: 4,
        kota: 0,
        totalSales: 34,
        number: "(+62) 331 4109 8667",
        email: "wsihombing@yahoo.com",
        location: "Tangerang Selatan",
        skill1:"S1 Biologi Institut Pertanian Bogor",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"Sabar dalam mengajar",
        statement:"EMANG IYA?",
    },
    {
        id: 7,
        name: "Dalimin Rajata",
        image:
            "https://randomuser.me/api/portraits/men/11.jpg",
        productType: "IPA",
        price: "55.000,00/Jam",
        pricePremium: "130.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 80,
        number: "(+62) 623 4247 8322",
        email: "wulandari.umi@gmail.com",
        location: "Jakarta",
        skill1:"S1 Kimia Murni Universitas Sebelas Maret",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"4 tahun menjadi guru Kimia SMA",
        statement:"EMANG IYA?",
    },
    {
        id: 8,
        name: "Shania Suryatmi ",
        image:
            "https://randomuser.me/api/portraits/women/95.jpg",
        productType: "IPA",
        price: "63.000,00/Jam",
        pricePremium: "138.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 13,
        number: "(+62) 987 1778 262",
        email: "putri.siregar@gmail.co.id",
        location: "Jakarta Selatan",
        skill1:"S1 Fisika Universitas Brawijaya ",
        skill2:"Mengajar untuk kelas 1-6",
        skill3:"5 Tahun menjadi guru IPA",
        statement:"EMANG IYA?",
    },
    {
        id: 9,
        name: "Iriana Sudiati",
        image:
            "https://randomuser.me/api/portraits/women/31.jpg",
        productType: "IPA",
        price: "57.000,00/Jam",
        pricePremium: "132.000,00/Jam",
        rating: 5,
        kota: 0,
        totalSales: 74,
        number: "(+62) 375 5324 197",
        email: "lailasari.abyasa@gmail.com",
        location: "Tangerang",
        skill1:"S1 Fisika Universitas Airlangga",
        skill2:"2 Tahun mengajar IPA",
        skill3:"Mengajar untuk kelas 1-6",
        statement:"EMANG IYA?",
    },

];
export default infoData;